language: r
cache: packages
sudo: false
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  _deploy.sh
env:
  global:
    secure: WK80H7XmHA0yqhTGsztD2VMD2Qa+GB0L9+9XY6Ed+jyqNKjPnvEix4OdHdHonqSH5ibXbV9izJ89ucSNiqGOaR6CwRmgnOBpvdpqMoGNZe/vNhwdxYzkbCuxXFloqQPBkzg6fCfZmpk++lmeyh4pAprPK8Mm1B41CSihsUeuvunQzLBS21zJh6oYWhaJarcMeZI9/33km7UgltKknF/U3rRq2e+XOQhHoE0EUaXHaFPRqiZbhB5So8ISSfARjbzPSO4Cm1apGGtes20gfXljTiewyob7dJw1GBKpuwoeVchml1cM/4T7Lw243UnjvaJJ+9Zy0ejOuXnPfdF7uZ/aBpV0kCPIFtjIVTPtf4oEpnv6h6kuw8nFbB1QDXY3Cs8/VaONw0Fnc5r6lkVRYgZkGqQtJKAYbgE2Nmzt7OS7iMMyOmDUCs8OxjdkGKgipHWipe65A9yukX/gmtWgYQxw/ouCDdPnrawZDIZvN9BjBye+M7OpqakprffOENWrYWrfAa+1jA58cTJj0ybsjhXiwB9bljX1BVAIB7A3L9pzkzUktcabvCe/y7YH3unbM3ipuQQ1JqBQNyJbKD6bhcRZPGeMAQmPeZ6MFMf4nlG83nPg2VJ2oXae8PybHXyj3D+dZxmNpwD9jBm6wuhxCUWCfj5EolBkWIEnPMddwLlLsls=
