language: r
sudo: false
cache:
  packages: true
  directories:
  - $HOME/.npm

before_install:
  - nvm install stable
  - npm install netlify-cli -g

env:
  - NETLIFY_SITE_ID=8a4ebbfd-3dcb-4ad7-86b2-0085312fd41a
  # NETLIFY_AUTH_TOKEN set in travis settings

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  - provider: script
    script: netlify deploy --dir _book
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"
  - provider: script
    script: netlify deploy --dir _book --prod
    skip_cleanup: true
    on:
      branch: master
